### ISSUE TITLE
Missing Module autocomplete.css

### ISSUE THREAD

**Issue by JCHHeilmann** [allenhwkim/geo-coder#3]
I'm using this geo-coder in my angular-meteor project. Every time the project is started this message appears in the console:

> Unable to resolve some modules:
> 
>   "!!../node_modules/css-loader/index.js!./autocomplete.css" in
> {path to project}/node_modules/geo-coder/dist/geocoder.umd.js
> (web.browser)

Any tips on how to resolve this? Thank you.

**Comment by allenhwkim** [comment]
Are you on the recent version? It does not use css anymore.

**Comment by jchheilmann** [comment]
Ah yes thank you. That was the issue. I thought I was, because there are only two releases liste here on github. But I found the newer ones on npm.
